name: Rust

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build executable
      run: cargo build --release --verbose
    - name: Build deb
      run: |
        cargo install cargo-deb
        cargo deb --separate-debug-symbols --compress-debug-symbols -v
    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: deb
        path: |
          target/release/webhookd
          target/debian/*.deb
